name: Toggle.Net Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
  
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Packages
      run: nuget restore Toggle.Net.sln

    - name: Build solution
      run: msbuild Toggle.Net.sln -t:rebuild -property:Configuration=Release

    - name: Run Tests
      run: packages\\NUnit.ConsoleRunner.3.17.0\\tools\\nunit3-console.exe tests\\Toggle.Net.Tests\\bin\\Release\\net452\\Toggle.Net.Tests.dll