name: Toggle.Net Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - run: echo "Building version 2.3.0$env:GITHUB_RUN_NUMBER"
    - uses: actions/checkout@v2
    - name: Setup .NET 4.5.2
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.5.2
    - name: Restore dependencies
      run: dotnet restore code\\Toggle.Net.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore code\\Toggle.Net.sln
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal code\\Toggle.Net.sln
    - name: NuGet Push
      run: dotnet nuget push "**/*.nupkg" --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
