name: Toggle.Net Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET Core 2.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.0.x
    - uses: kzrnm/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: code/Toggle.Net/Toggle.Net.csproj
    - run: echo HELLO THERE!
    - run: echo "${{steps.get-version.outputs.version}}"
    - run: echo "${{steps.get-version.outputs.version-prefix}}"
    - run: echo "${{steps.get-version.outputs.version-suffix}}"
    - run: echo "${{steps.get-version.outputs.package-version}}"
    - run: echo "${{steps.get-version.outputs.assembly-version}}"
    - run: echo "${{steps.get-version.outputs.file-version}}"
    - run: echo "${{steps.get-version.outputs.informational-version}}"
    - run: echo "2.3.$GITHUB_RUN_ID.$GITHUB_RUN_NUMBER"
    - run: echo $GITHUB_RUN_ID
    - run: echo $GITHUB_RUN_NUMBER
    - run: echo "$GITHUB_RUN_ID"
    - run: echo "$GITHUB_RUN_NUMBER"
    - run: echo "Deploying to production server on branch $GITHUB_REF"
    - run: echo "Deploying to production server on branch $env:GITHUB_REF"
    - run: echo "$env:GITHUB_RUN_ID"
    - run: echo "$env:GITHUB_RUN_NUMBER"
    - run: echo "2.3.0$env:GITHUB_RUN_NUMBER"
    - name: Restore dependencies
      run: dotnet restore code\\Toggle.Net.sln
    - name: Build
      run: dotnet build --no-restore code\\Toggle.Net.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal code\\Toggle.Net.sln
