name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET Core 2.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.0.x
    - name: Restore dependencies
      run: dotnet restore code\\Toggle.Net.sln
    - name: Build
      run: dotnet build --no-restore code\\Toggle.Net.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal code\\Toggle.Net.sln
